# Site settings
title: James McCann
email: jmccnz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  James McCann, software developer based in Wellington, New Zealand.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jamesmccann.nz" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
highlighter: 'pygments'
